<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MetroDisplay.Contracts\MetroDisplay.Contracts.csproj" />
    <ProjectReference Include="..\MetroDisplay.Gtfs.Static\MetroDisplay.Gtfs.Static.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
